version: "3.9"

services:
  web-app:
    build: .
    deploy:
      replicas: 2
  reverse-proxy:
    build: entry
    ports:
      - 8080:8080
  load-balancer-master:
    build:
      context: load-balancer
      args:
        role: master
    cap_add:
      - NET_ADMIN
  load-balancer-backup:
    build:
      context: load-balancer
      args:
        role: backup
    cap_add:
      - NET_ADMIN

networks:
  default:
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
